version: '3.8'

services:
  ecommbackend:
    image: ecommbackend
    build:
      context: backend
      dockerfile: Dockerfile
    env_file:
      - ./backend/.env
    ports:
      - "4000:4000"
    networks:
      - e-comm-network

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - e-comm-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: e-comm-frontend
    ports:
      - "3000:80"
    networks:
      - e-comm-network

volumes:
  mongo-data:

networks:
  e-comm-network:
    external: true
